apiVersion: v1
data:
  API_ENV_VAL: "1"
kind: ConfigMap
metadata:
  labels:
    tier: backend
  name: api-env-1

---
apiVersion: v1
data:
  API_ENV_VAL: "2"
kind: ConfigMap
metadata:
  labels:
    tier: backend
  name: api-env-2