namespace: managed-redis
resources:
- deployment.yaml
- ingress.yaml
- rollout.yaml
- services.yaml
configMapGenerator:
- literals:
    - API_ENV_VAL=1
    - TEST_VAL_1=1
    - TEST_VAL_2=2
    - TEST_VAL_3=3
    - TEST_VAL_4=4
  name: rollouts-demo-env