# This example demonstrates a Rollout which begins an an experiment at a specified step.
# The rollout will not proceed to the next step until the experiment is completed and successful.
# In this example, the experiment itself starts its own AnalysisRun which is tied to the experiment.
# This is useful for when analysis should be done only during the experimentation phase, but not
# during the regular update of the rollout.
#
# Prerequisites:
# * kubectl apply -f analysis-templates.yaml
#
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-experiment-step
spec:
  replicas: 1
  revisionHistoryLimit: 2
  rollbackWindow:
    revisions: 2
  analysis:
    # limits the number of successful analysis runs and experiments to be stored in a history
    # Defaults to 5.
    successfulRunHistoryLimit: 2
    # limits the number of unsuccessful analysis runs and experiments to be stored in a history.
    # Stages for unsuccessful: "Error", "Failed", "Inconclusive"
    # Defaults to 5.
    unsuccessfulRunHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-experiment-step
  template:
    metadata:
      labels:
        app: rollout-experiment-step
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        # image: argoproj/rollouts-demo:yellow
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      # The second step is the experiment which starts a single canary pod
      - experiment:
          # duration: 10s
          templates:
          - name: canary
            specRef: canary
            service:
              name: canary
          # This experiment performs its own analysis by referencing one or more AnalysisTemplates
          # here. The success or failure of these runs will progress or abort the rollout respectively.
          analyses:
          # - name: random-fail
          #   templateName: random-fail

          - name: pass
            templateName: pass
            requiredForCompletion: true

          # - name: fail
          #   templateName: fail
          #   requiredForCompletion: true
          # - name: sleep
          #   templateName: sleep
          #   requiredForCompletion: true
